name: Automated tag with autotag
description: Automatically create tags for conventional commits
author: oobook
branding:
  icon: target
  color: yellow
inputs:
  owner:
    description: "The owner of the repository (user or org)"
    required: true
  repo:
    description: "The repository name"
    required: true
  pr-number:
    description: "The number of the pull request"
    required: true
  token:
    description: "The token to use to access the Github API"
    required: true
  gh-token:
    description: GitHub token with repo access
    required: true
  test:
    description: run mode of the action
    required: false
    default: false
# runs:
#   using: composite
#   steps:
#     - uses: actions/checkout@v3
#     - name: Tag & Release
#       shell: bash
#       run: sh ${{ github.action_path }}/src/create-tag.sh
#       env:
#         GITHUB_TOKEN: ${{ inputs.gh-token }}
runs:
  using: node20
  main: dist/index.js
