name: Main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - dev
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./
        id: tag-generation
        # if: ${{ success() && secrets.GITHUB_TOKEN != '' }}
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          test: true
