name: Main
on:
  push:
    branches:
      - main
    # branches-ignore:
    #   - 'mona/octocat'
    #   - 'releases/**-alpha'
    # Sequence of patterns matched against refs/tags
    tags-ignore:
      - v2
      - v1.*
  pull_request:
    branches:
      - dev

permissions:
  contents: write
  
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./
        id: tag-generation
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Workflow (if not BREAKING CHANGE)
        id: release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          automatic_release_tag: "${{ steps.tag-generation.outputs.tag }}"
      - name: Handle Releasing Output
        run: |
          echo "Released Tag {{ steps.release.outputs.automatic_releases_tag }}"
          echo "Upload Url {{ steps.release.outputs.upload_url }}"