name: Main
on:
  push:
    branches:
      - main
    tags-ignore:
      - v*

permissions:
  contents: write
  
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create Tag
        uses: ./
        id: tag-generation
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        uses: oobook/automated-release@v1.0.1
        id: release-generation
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          tag: "${{ steps.tag-generation.outputs.tag }}"
          prerelease: true