name: Create Release

# Run on every commit tag which begins with 'v' except BREAKING Change
on:
  repository_dispatch:
    types: [new-tag-created]

permissions:
  contents: write

# Automatically create a Github Release, with release details specified (the relevant commits)
jobs:
  release:
    name: "Release the new version from the related tag"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # This ensures all history is fetched
      - name: Run Workflow (if not BREAKING CHANGE)
        id: release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          title: "Release ${{ github.event.client_payload.tag }}"
      - name: Handle Releasing Output
        run: |
          echo "Released Tag {{ steps.releas.outputs.automatic_releases_tag }}"
          echo "Upload Url {{ steps.releas.outputs.upload_url }}"
